/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashoncardproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Granson
 */
public class SignIn extends javax.swing.JFrame {

    Connection conn = null;

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        conn = DataBaseConnector.newConnection();
        initComponents();
    }

    //Checks if user is in database

    private void checkUser() {
        if (cardTxt.getText().equals("") || passText.getText().equals("") || mailTxt.getText().equals("")) {
            JOptionPane
                    .showMessageDialog(
                            null,
                            "Please fill all The Entries appropriately and try again");
        } else {
            try {
                String sql = "select * from MembersTable where cardnumber = " + cardTxt.getText();
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {

                    JOptionPane
                            .showMessageDialog(
                                    null,
                                    "The items article already exists in the database,or"
                                    + " some entries can't be verified as  valid data types variables");
                } else {
                    signMeUp();
                }
                ps.close();
                rs.close();

            } catch (SQLException ex) {
                Logger.getLogger(MembersGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    //Adds user to database
    private void signMeUp() {
        try {
            String query = "insert into MembersTable (email,name,phone_no,address,cardnumber,card_expiry_date,password) values(?,?,?,?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, mailTxt.getText());
            ps.setString(2, nameTxt.getText());
            ps.setString(3, phoneTXT.getText());
            ps.setString(4, addressTxt.getText());
            ps.setString(5, cardTxt.getText());
            ps.setString(6, "*** *** *** **");
            ps.setString(7, passText.getText());

            ps.execute();
            JOptionPane.showMessageDialog(null,
                    "Submitted successfully !!!");
             int action = JOptionPane.showConfirmDialog(null,
                    "Would you like to sign in now ?", "Sign in Prompt",
                    JOptionPane.YES_NO_OPTION);
            if (action == 0) {

                LoginClass log = new LoginClass();
                log.setVisible(true);
                dispose();
            }else
            {
                
            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            JOptionPane
                    .showMessageDialog(
                            null, e
                            + "\n{ The items article already exists in the database,or"
                            + " can't be verified as a valid data variable");

            int action = JOptionPane.showConfirmDialog(null,
                    "\n{ The items article already exists in the database,or"
                    + " can't be verified as a valid data variable}\n Contact Administrator for more infomation", "Sign up error Prompt",
                    JOptionPane.YES_NO_OPTION);
            if (action == 0) {

                JOptionPane.showMessageDialog(null, "Connects to the company's website for FAQs");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameTxt = new javax.swing.JTextField();
        mailTxt = new javax.swing.JTextField();
        phoneTXT = new javax.swing.JTextField();
        cardTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        PassCheckBtn = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("AR JULIAN", 1, 24)); // NOI18N
        jLabel1.setText("Sign Up Frame");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nameTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nameTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Name :"));

        mailTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        mailTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Email Address:"));

        phoneTXT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        phoneTXT.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Number:"));

        cardTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cardTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Card Number:"));

        addressTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        addressTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Residential Address:"));

        passText.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        passText.setBorder(javax.swing.BorderFactory.createTitledBorder("Password :"));
        passText.setEchoChar('%');

        PassCheckBtn.setBackground(new java.awt.Color(255, 255, 255));
        PassCheckBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        PassCheckBtn.setText("Show Password");
        PassCheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassCheckBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PassCheckBtn))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PassCheckBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Welcome New Member,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PassCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassCheckBtnActionPerformed
        // TODO add your handling code here:
        if (PassCheckBtn.isSelected()) {
            passText.setEchoChar((char) 0);
        } else {
            passText.setEchoChar(('%'));
        }

    }//GEN-LAST:event_PassCheckBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        checkUser();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox PassCheckBtn;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField cardTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passText;
    private javax.swing.JTextField phoneTXT;
    // End of variables declaration//GEN-END:variables
}
